// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOTPCredentialByEmail = `-- name: GetOTPCredentialByEmail :one
SELECT
    oc.id,
    oc.pid,
    oc.principal_id,
    oc.email,
    oc.verified_at,
    oc.disabled_at AS credential_disabled_at,
    p.disabled_at AS principal_disabled_at,
    p.auth_invalidated_at,
    p.created_at AS principal_created_at
FROM
    email_otp_credentials oc
    JOIN principals p ON p.id = oc.principal_id
WHERE
    oc.email = $1
`

type GetOTPCredentialByEmailRow struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	Pid                  string             `db:"pid" json:"pid"`
	PrincipalID          uuid.UUID          `db:"principal_id" json:"principalId"`
	Email                string             `db:"email" json:"email"`
	VerifiedAt           pgtype.Timestamptz `db:"verified_at" json:"verifiedAt"`
	CredentialDisabledAt pgtype.Timestamptz `db:"credential_disabled_at" json:"credentialDisabledAt"`
	PrincipalDisabledAt  pgtype.Timestamptz `db:"principal_disabled_at" json:"principalDisabledAt"`
	AuthInvalidatedAt    pgtype.Timestamptz `db:"auth_invalidated_at" json:"authInvalidatedAt"`
	PrincipalCreatedAt   pgtype.Timestamptz `db:"principal_created_at" json:"principalCreatedAt"`
}

func (q *Queries) GetOTPCredentialByEmail(ctx context.Context, email string) (GetOTPCredentialByEmailRow, error) {
	row := q.db.QueryRow(ctx, getOTPCredentialByEmail, email)
	var i GetOTPCredentialByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.PrincipalID,
		&i.Email,
		&i.VerifiedAt,
		&i.CredentialDisabledAt,
		&i.PrincipalDisabledAt,
		&i.AuthInvalidatedAt,
		&i.PrincipalCreatedAt,
	)
	return i, err
}

const getPasswordCredentialByEmail = `-- name: GetPasswordCredentialByEmail :one
SELECT
    pc.id,
    pc.pid,
    pc.principal_id,
    pc.email,
    pc.password_hash,
    pc.password_updated_at,
    pc.disabled_at AS credential_disabled_at,
    p.disabled_at AS principal_disabled_at,
    p.auth_invalidated_at,
    p.created_at AS principal_created_at
FROM
    password_credentials pc
    JOIN principals p ON p.id = pc.principal_id
WHERE
    pc.email = $1
`

type GetPasswordCredentialByEmailRow struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	Pid                  string             `db:"pid" json:"pid"`
	PrincipalID          uuid.UUID          `db:"principal_id" json:"principalId"`
	Email                string             `db:"email" json:"email"`
	PasswordHash         string             `db:"password_hash" json:"passwordHash"`
	PasswordUpdatedAt    pgtype.Timestamptz `db:"password_updated_at" json:"passwordUpdatedAt"`
	CredentialDisabledAt pgtype.Timestamptz `db:"credential_disabled_at" json:"credentialDisabledAt"`
	PrincipalDisabledAt  pgtype.Timestamptz `db:"principal_disabled_at" json:"principalDisabledAt"`
	AuthInvalidatedAt    pgtype.Timestamptz `db:"auth_invalidated_at" json:"authInvalidatedAt"`
	PrincipalCreatedAt   pgtype.Timestamptz `db:"principal_created_at" json:"principalCreatedAt"`
}

func (q *Queries) GetPasswordCredentialByEmail(ctx context.Context, email string) (GetPasswordCredentialByEmailRow, error) {
	row := q.db.QueryRow(ctx, getPasswordCredentialByEmail, email)
	var i GetPasswordCredentialByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.PrincipalID,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordUpdatedAt,
		&i.CredentialDisabledAt,
		&i.PrincipalDisabledAt,
		&i.AuthInvalidatedAt,
		&i.PrincipalCreatedAt,
	)
	return i, err
}

const getPrincipalAuthState = `-- name: GetPrincipalAuthState :one
SELECT
    disabled_at,
    auth_invalidated_at
FROM
    principals
WHERE
    id = $1
`

type GetPrincipalAuthStateRow struct {
	DisabledAt        pgtype.Timestamptz `db:"disabled_at" json:"disabledAt"`
	AuthInvalidatedAt pgtype.Timestamptz `db:"auth_invalidated_at" json:"authInvalidatedAt"`
}

func (q *Queries) GetPrincipalAuthState(ctx context.Context, id uuid.UUID) (GetPrincipalAuthStateRow, error) {
	row := q.db.QueryRow(ctx, getPrincipalAuthState, id)
	var i GetPrincipalAuthStateRow
	err := row.Scan(&i.DisabledAt, &i.AuthInvalidatedAt)
	return i, err
}

const getPrincipalByUserEmail = `-- name: GetPrincipalByUserEmail :one
SELECT
    p.id, p.pid, p.kind, p.disabled_at, p.auth_invalidated_at, p.created_at, p.updated_at
FROM
    users u
    JOIN principals p ON p.id = u.principal_id
WHERE
    u.email = $1
`

func (q *Queries) GetPrincipalByUserEmail(ctx context.Context, email string) (Principal, error) {
	row := q.db.QueryRow(ctx, getPrincipalByUserEmail, email)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Kind,
		&i.DisabledAt,
		&i.AuthInvalidatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPrincipalID = `-- name: GetUserByPrincipalID :one
SELECT
    id, pid, principal_id, email, name, is_staff, created_at, updated_at
FROM
    users
WHERE
    principal_id = $1
`

func (q *Queries) GetUserByPrincipalID(ctx context.Context, principalID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPrincipalID, principalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.PrincipalID,
		&i.Email,
		&i.Name,
		&i.IsStaff,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembershipsForPrincipal = `-- name: ListMembershipsForPrincipal :many
SELECT
    m.id,
    m.pid,
    m.role,
    m.scope_id,
    s.kind AS scope_kind,
    o.pid AS org_pid,
    o.name AS org_name,
    o.slug AS org_slug,
    t.pid AS team_pid,
    t.name AS team_name,
    t.slug AS team_slug
FROM
    memberships m
    JOIN scopes s ON s.id = m.scope_id
    JOIN orgs o ON o.scope_id = s.id
    JOIN teams t ON t.scope_id = s.id
WHERE
    m.principal_id = $1
`

type ListMembershipsForPrincipalRow struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	Pid       string      `db:"pid" json:"pid"`
	Role      interface{} `db:"role" json:"role"`
	ScopeID   uuid.UUID   `db:"scope_id" json:"scopeId"`
	ScopeKind interface{} `db:"scope_kind" json:"scopeKind"`
	OrgPid    string      `db:"org_pid" json:"orgPid"`
	OrgName   string      `db:"org_name" json:"orgName"`
	OrgSlug   string      `db:"org_slug" json:"orgSlug"`
	TeamPid   string      `db:"team_pid" json:"teamPid"`
	TeamName  string      `db:"team_name" json:"teamName"`
	TeamSlug  string      `db:"team_slug" json:"teamSlug"`
}

func (q *Queries) ListMembershipsForPrincipal(ctx context.Context, principalID uuid.UUID) ([]ListMembershipsForPrincipalRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsForPrincipalRow{}
	for rows.Next() {
		var i ListMembershipsForPrincipalRow
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.Role,
			&i.ScopeID,
			&i.ScopeKind,
			&i.OrgPid,
			&i.OrgName,
			&i.OrgSlug,
			&i.TeamPid,
			&i.TeamName,
			&i.TeamSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchPrincipalAuthInvalidatedAt = `-- name: TouchPrincipalAuthInvalidatedAt :exec
UPDATE principals
SET
    auth_invalidated_at = now()
WHERE
    id = $1
`

func (q *Queries) TouchPrincipalAuthInvalidatedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchPrincipalAuthInvalidatedAt, id)
	return err
}

const updatePasswordCredentialHash = `-- name: UpdatePasswordCredentialHash :exec
UPDATE password_credentials
SET
    password_hash = $2,
    password_updated_at = now()
WHERE
    principal_id = $1
`

type UpdatePasswordCredentialHashParams struct {
	PrincipalID  uuid.UUID `db:"principal_id" json:"principalId"`
	PasswordHash string    `db:"password_hash" json:"passwordHash"`
}

func (q *Queries) UpdatePasswordCredentialHash(ctx context.Context, arg UpdatePasswordCredentialHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordCredentialHash, arg.PrincipalID, arg.PasswordHash)
	return err
}
