// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package sqlc

import (
	"context"
)

const healthCheck = `-- name: HealthCheck :one
SELECT
  now()::text AS now
`

func (q *Queries) HealthCheck(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, healthCheck)
	var now string
	err := row.Scan(&now)
	return now, err
}
