// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type UserRole string

const (
	UserRoleOwner  UserRole = "owner"
	UserRoleAdmin  UserRole = "admin"
	UserRoleMember UserRole = "member"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"userRole"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Team struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Pid       string             `db:"pid" json:"pid"`
	Name      string             `db:"name" json:"name"`
	Slug      string             `db:"slug" json:"slug"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type TeamMembership struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Pid       string             `db:"pid" json:"pid"`
	TeamID    uuid.UUID          `db:"team_id" json:"teamId"`
	UserID    uuid.UUID          `db:"user_id" json:"userId"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type User struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	Pid               string             `db:"pid" json:"pid"`
	Email             string             `db:"email" json:"email"`
	Name              string             `db:"name" json:"name"`
	Role              UserRole           `db:"role" json:"role"`
	PasswordHash      *string            `db:"password_hash" json:"passwordHash"`
	PasswordUpdatedAt pgtype.Timestamptz `db:"password_updated_at" json:"passwordUpdatedAt"`
	DisabledAt        pgtype.Timestamptz `db:"disabled_at" json:"disabledAt"`
	AuthInvalidatedAt pgtype.Timestamptz `db:"auth_invalidated_at" json:"authInvalidatedAt"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}
