// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	HealthCheck(ctx context.Context) (string, error)
}

var _ Querier = (*Queries)(nil)
