// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreatePrincipal(ctx context.Context, arg CreatePrincipalParams) (Principal, error)
	HealthCheck(ctx context.Context) (string, error)
	UpsertUserForSeed(ctx context.Context, arg UpsertUserForSeedParams) (User, error)
}

var _ Querier = (*Queries)(nil)
