// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPrincipal = `-- name: CreatePrincipal :one
INSERT INTO
    principals (id, kind)
VALUES
    ($1, $2::principal_kind)
ON CONFLICT (id) DO UPDATE
SET
    kind = EXCLUDED.kind
RETURNING
    id, pid, kind, disabled_at, auth_invalidated_at, created_at, updated_at
`

type CreatePrincipalParams struct {
	ID   uuid.UUID     `db:"id" json:"id"`
	Kind PrincipalKind `db:"kind" json:"kind"`
}

func (q *Queries) CreatePrincipal(ctx context.Context, arg CreatePrincipalParams) (Principal, error) {
	row := q.db.QueryRow(ctx, createPrincipal, arg.ID, arg.Kind)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Kind,
		&i.DisabledAt,
		&i.AuthInvalidatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserForSeed = `-- name: UpsertUserForSeed :one
INSERT INTO
    users (principal_id, email, name, is_staff)
VALUES
    ($1, $2, $3, $4)
ON CONFLICT (email) DO UPDATE
SET
    name = EXCLUDED.name,
    is_staff = EXCLUDED.is_staff
RETURNING
    id, pid, principal_id, email, name, is_staff, created_at, updated_at
`

type UpsertUserForSeedParams struct {
	PrincipalID uuid.UUID `db:"principal_id" json:"principalId"`
	Email       string    `db:"email" json:"email"`
	Name        string    `db:"name" json:"name"`
	IsStaff     bool      `db:"is_staff" json:"isStaff"`
}

func (q *Queries) UpsertUserForSeed(ctx context.Context, arg UpsertUserForSeedParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserForSeed,
		arg.PrincipalID,
		arg.Email,
		arg.Name,
		arg.IsStaff,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.PrincipalID,
		&i.Email,
		&i.Name,
		&i.IsStaff,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
