// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const upsertTeamForSeed = `-- name: UpsertTeamForSeed :one
INSERT INTO
    teams (id, name, slug)
VALUES
    ($1, $2, $3)
ON CONFLICT (slug) DO UPDATE
SET
    name = EXCLUDED.name,
    slug = EXCLUDED.slug
RETURNING
    id, pid, name, slug, created_at, updated_at
`

type UpsertTeamForSeedParams struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Name string    `db:"name" json:"name"`
	Slug string    `db:"slug" json:"slug"`
}

func (q *Queries) UpsertTeamForSeed(ctx context.Context, arg UpsertTeamForSeedParams) (Team, error) {
	row := q.db.QueryRow(ctx, upsertTeamForSeed, arg.ID, arg.Name, arg.Slug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTeamMembershipForSeed = `-- name: UpsertTeamMembershipForSeed :one
INSERT INTO
    team_memberships (id, team_id, user_id)
VALUES
    ($1, $2, $3)
ON CONFLICT (id) DO UPDATE
SET
    team_id = EXCLUDED.team_id,
    user_id = EXCLUDED.user_id
RETURNING
    id, pid, team_id, user_id, created_at, updated_at
`

type UpsertTeamMembershipForSeedParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"teamId"`
	UserID uuid.UUID `db:"user_id" json:"userId"`
}

func (q *Queries) UpsertTeamMembershipForSeed(ctx context.Context, arg UpsertTeamMembershipForSeedParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, upsertTeamMembershipForSeed, arg.ID, arg.TeamID, arg.UserID)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.TeamID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserForSeed = `-- name: UpsertUserForSeed :one
INSERT INTO
    users (id, email, name, role, password_hash)
VALUES
    ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
SET
    email = EXCLUDED.email,
    name = EXCLUDED.name,
    role = EXCLUDED.role,
    password_hash = EXCLUDED.password_hash
RETURNING
    id, pid, email, name, role, password_hash, password_updated_at, disabled_at, auth_invalidated_at, created_at, updated_at
`

type UpsertUserForSeedParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Email        string    `db:"email" json:"email"`
	Name         string    `db:"name" json:"name"`
	Role         UserRole  `db:"role" json:"role"`
	PasswordHash *string   `db:"password_hash" json:"passwordHash"`
}

func (q *Queries) UpsertUserForSeed(ctx context.Context, arg UpsertUserForSeedParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserForSeed,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.PasswordUpdatedAt,
		&i.DisabledAt,
		&i.AuthInvalidatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
