// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createOrgScopeForSeed = `-- name: CreateOrgScopeForSeed :one
INSERT INTO
    scopes (kind, parent_id)
VALUES
    ('org', NULL)
RETURNING
    id, pid, kind, parent_id, created_at, updated_at
`

func (q *Queries) CreateOrgScopeForSeed(ctx context.Context) (Scope, error) {
	row := q.db.QueryRow(ctx, createOrgScopeForSeed)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Kind,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPrincipal = `-- name: CreatePrincipal :one
INSERT INTO
    principals (kind)
VALUES
    ($1)
RETURNING
    id, pid, kind, disabled_at, auth_invalidated_at, created_at, updated_at
`

func (q *Queries) CreatePrincipal(ctx context.Context, kind interface{}) (Principal, error) {
	row := q.db.QueryRow(ctx, createPrincipal, kind)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Kind,
		&i.DisabledAt,
		&i.AuthInvalidatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeamScopeForSeed = `-- name: CreateTeamScopeForSeed :one
INSERT INTO
    scopes (kind, parent_id)
VALUES
    ('team', $1)
RETURNING
    id, pid, kind, parent_id, created_at, updated_at
`

func (q *Queries) CreateTeamScopeForSeed(ctx context.Context, parentID uuid.NullUUID) (Scope, error) {
	row := q.db.QueryRow(ctx, createTeamScopeForSeed, parentID)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Kind,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgBySlug = `-- name: GetOrgBySlug :one
SELECT
    id, pid, scope_id, name, slug, created_at, updated_at
FROM
    orgs
WHERE
    slug = $1
`

func (q *Queries) GetOrgBySlug(ctx context.Context, slug string) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgBySlug, slug)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.ScopeID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByOrgAndSlug = `-- name: GetTeamByOrgAndSlug :one
SELECT
    id, pid, scope_id, org_id, parent_team_id, name, slug, created_at, updated_at
FROM
    teams
WHERE
    org_id = $1
    AND slug = $2
`

type GetTeamByOrgAndSlugParams struct {
	OrgID uuid.UUID `db:"org_id" json:"orgId"`
	Slug  string    `db:"slug" json:"slug"`
}

func (q *Queries) GetTeamByOrgAndSlug(ctx context.Context, arg GetTeamByOrgAndSlugParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByOrgAndSlug, arg.OrgID, arg.Slug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.ScopeID,
		&i.OrgID,
		&i.ParentTeamID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id, pid, principal_id, email, name, is_staff, created_at, updated_at
FROM
    users
WHERE
    email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.PrincipalID,
		&i.Email,
		&i.Name,
		&i.IsStaff,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMembershipForSeed = `-- name: UpsertMembershipForSeed :one
INSERT INTO
    memberships (scope_id, principal_id, role)
VALUES
    ($1, $2, $3)
ON CONFLICT (scope_id, principal_id) DO UPDATE
SET role = EXCLUDED.role
RETURNING
    id, pid, scope_id, principal_id, role, joined_at, created_at, updated_at
`

type UpsertMembershipForSeedParams struct {
	ScopeID     uuid.UUID   `db:"scope_id" json:"scopeId"`
	PrincipalID uuid.UUID   `db:"principal_id" json:"principalId"`
	Role        interface{} `db:"role" json:"role"`
}

func (q *Queries) UpsertMembershipForSeed(ctx context.Context, arg UpsertMembershipForSeedParams) (Membership, error) {
	row := q.db.QueryRow(ctx, upsertMembershipForSeed, arg.ScopeID, arg.PrincipalID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.ScopeID,
		&i.PrincipalID,
		&i.Role,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOTPCredentialForSeed = `-- name: UpsertOTPCredentialForSeed :one
INSERT INTO
    email_otp_credentials (principal_id, email, verified_at)
VALUES
    ($1, $2, now())
ON CONFLICT (email) DO UPDATE
SET
    verified_at = COALESCE(email_otp_credentials.verified_at, now())
RETURNING
    id, pid, principal_id, email, verified_at, disabled_at, created_at, updated_at
`

type UpsertOTPCredentialForSeedParams struct {
	PrincipalID uuid.UUID `db:"principal_id" json:"principalId"`
	Email       string    `db:"email" json:"email"`
}

func (q *Queries) UpsertOTPCredentialForSeed(ctx context.Context, arg UpsertOTPCredentialForSeedParams) (EmailOtpCredential, error) {
	row := q.db.QueryRow(ctx, upsertOTPCredentialForSeed, arg.PrincipalID, arg.Email)
	var i EmailOtpCredential
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.PrincipalID,
		&i.Email,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrgForSeed = `-- name: UpsertOrgForSeed :one
INSERT INTO
    orgs (scope_id, name, slug)
VALUES
    ($1, $2, $3)
ON CONFLICT (slug) DO UPDATE
SET
    name = EXCLUDED.name
RETURNING
    id, pid, scope_id, name, slug, created_at, updated_at
`

type UpsertOrgForSeedParams struct {
	ScopeID uuid.UUID `db:"scope_id" json:"scopeId"`
	Name    string    `db:"name" json:"name"`
	Slug    string    `db:"slug" json:"slug"`
}

func (q *Queries) UpsertOrgForSeed(ctx context.Context, arg UpsertOrgForSeedParams) (Org, error) {
	row := q.db.QueryRow(ctx, upsertOrgForSeed, arg.ScopeID, arg.Name, arg.Slug)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.ScopeID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPasswordCredentialForSeed = `-- name: UpsertPasswordCredentialForSeed :one
INSERT INTO
    password_credentials (principal_id, email, password_hash)
VALUES
    ($1, $2, $3)
ON CONFLICT (email) DO UPDATE
SET
    password_hash = EXCLUDED.password_hash
RETURNING
    id, pid, principal_id, email, password_hash, password_updated_at, disabled_at, created_at, updated_at
`

type UpsertPasswordCredentialForSeedParams struct {
	PrincipalID  uuid.UUID `db:"principal_id" json:"principalId"`
	Email        string    `db:"email" json:"email"`
	PasswordHash string    `db:"password_hash" json:"passwordHash"`
}

func (q *Queries) UpsertPasswordCredentialForSeed(ctx context.Context, arg UpsertPasswordCredentialForSeedParams) (PasswordCredential, error) {
	row := q.db.QueryRow(ctx, upsertPasswordCredentialForSeed, arg.PrincipalID, arg.Email, arg.PasswordHash)
	var i PasswordCredential
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.PrincipalID,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordUpdatedAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTeamForSeed = `-- name: UpsertTeamForSeed :one
INSERT INTO
    teams (scope_id, org_id, parent_team_id, name, slug)
VALUES
    ($1, $2, $3, $4, $5)
ON CONFLICT (slug) DO UPDATE
SET
    name = EXCLUDED.name,
    parent_team_id = EXCLUDED.parent_team_id
RETURNING
    id, pid, scope_id, org_id, parent_team_id, name, slug, created_at, updated_at
`

type UpsertTeamForSeedParams struct {
	ScopeID      uuid.UUID     `db:"scope_id" json:"scopeId"`
	OrgID        uuid.UUID     `db:"org_id" json:"orgId"`
	ParentTeamID uuid.NullUUID `db:"parent_team_id" json:"parentTeamId"`
	Name         string        `db:"name" json:"name"`
	Slug         string        `db:"slug" json:"slug"`
}

func (q *Queries) UpsertTeamForSeed(ctx context.Context, arg UpsertTeamForSeedParams) (Team, error) {
	row := q.db.QueryRow(ctx, upsertTeamForSeed,
		arg.ScopeID,
		arg.OrgID,
		arg.ParentTeamID,
		arg.Name,
		arg.Slug,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.ScopeID,
		&i.OrgID,
		&i.ParentTeamID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserForSeed = `-- name: UpsertUserForSeed :one
INSERT INTO
    users (principal_id, email, name, is_staff)
VALUES
    ($1, $2, $3, $4)
ON CONFLICT (email) DO UPDATE
SET
    name = EXCLUDED.name,
    is_staff = EXCLUDED.is_staff
RETURNING
    id, pid, principal_id, email, name, is_staff, created_at, updated_at
`

type UpsertUserForSeedParams struct {
	PrincipalID uuid.UUID `db:"principal_id" json:"principalId"`
	Email       string    `db:"email" json:"email"`
	Name        string    `db:"name" json:"name"`
	IsStaff     bool      `db:"is_staff" json:"isStaff"`
}

func (q *Queries) UpsertUserForSeed(ctx context.Context, arg UpsertUserForSeedParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserForSeed,
		arg.PrincipalID,
		arg.Email,
		arg.Name,
		arg.IsStaff,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.PrincipalID,
		&i.Email,
		&i.Name,
		&i.IsStaff,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
